accumulate_grad_batches: 1
adafactor: false
adam_epsilon: 1.0e-08
attention_dropout: null
cache_dir: ''
command: train
config_name: klue_resources
data_dir: data/klue_benchmark/klue-re-v1.1
dataset_size: 32470
decoder_layerdrop: null
dev_file_name: null
dropout: null
early_stopping_mode: max
encoder_layerdrop: null
eval_batch_size: 64
fp16: false
gpus:
- 0
gradient_clip_val: 1.0
label_list:
- no_relation
- org:dissolved
- org:founded
- org:place_of_headquarters
- org:alternate_names
- org:member_of
- org:members
- org:political/religious_affiliation
- org:product
- org:founded_by
- org:top_members/employees
- org:number_of_employees/members
- per:date_of_birth
- per:date_of_death
- per:place_of_birth
- per:place_of_death
- per:place_of_residence
- per:origin
- per:employee_of
- per:schools_attended
- per:alternate_names
- per:parents
- per:children
- per:siblings
- per:spouse
- per:other_family
- per:colleagues
- per:product
- per:religion
- per:title
learning_rate: 5.0e-05
lr_scheduler: linear
max_epochs: 3
max_seq_length: 128
metric_key: micro_f1
model_name_or_path: klue_resources
num_gpus: 1
num_labels: 30
num_sanity_val_steps: 2
num_workers: 16
output_dir: klue_output/klue-re/version_0
patience: 10000
relation_filename: relation_list.json
seed: 42
task: klue-re
test_file_name: null
tokenizer_name: klue_resources
tpu_cores: null
train_batch_size: 32
train_file_name: null
verbose_step_count: 100
warmup_ratio: 0.1
warmup_steps: null
weight_decay: 0.0
